sudo: required
services:
  - docker

before_install:
  - docker build -t charltonz/docker-react -f Dockerfile.dev .

script:
  - docker run charltonz/docker-react npm run test -- --coverage -e CI=true
